### ISSUE TITLE
 ValueError: Variable d_w1/Adam_5/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

### ISSUE THREAD

**Issue by zfk513** [jonbruner/generative-adversarial-networks#6]
Help~!!!!

**Comment by JustinMBrown** [comment]
Which version of TF are you using, and which script are you running?

**Comment by zfk513** [comment]
@JustinMBrown While  the latest the TF,and the script gan-script-fast.py
i try it on colab as well ,failed as well

**Comment by jonbruner** [comment]
A few people were getting this error during the TF 1.0 to TF 1.1 era: https://github.com/jonbruner/generative-adversarial-networks/issues/1. The issue was scoping, but I think we resolved it with a small restructuring.

I've just re-run everything with TensorFlow 1.8 and can't duplicate your error. Could you confirm that you're running TF 1.8 and see if you're still getting it?
